// TODO: we want this to be dynamic, or parameterized or something
// Tricky because the contents of this include the imports which have a bunch
// of dynamic symbols (I think generated by wasm_bindgen)
// import { default as init } from './boot.js'
import { default as init } from './pkg/widgetry_demo.js'

export class SimulationConfig {
   wasmURL: URL;

   public constructor() {
        //this.wasmURL = new URL('http://abstreet.s3-website.us-east-2.amazonaws.com/dev/game/game_bg.wasm');
        this.wasmURL = new URL('http://localhost:4000/js/pkg/widgetry_demo_bg.wasm');
   } 

   public wasmURLString() {
       return this.wasmURL.toString()
   }
}

export enum SimulationLoadState {
    unloaded, loading, loaded, error
}

export class Simulation {
    el: HTMLElement;
    config: SimulationConfig;
    state: SimulationLoadState = SimulationLoadState.unloaded;

    public constructor(el: HTMLElement) {
        this.el = el;
        appendLoading(this.el);
        this.config = new SimulationConfig();
        this.render();

        console.log("sim constructor", this);
    }

    public async loadAndStart() {
        try {
            await this.load();
            await this.start();
        } catch (e) {
            if (e.toString() == "Error: Using exceptions for control flow, don't mind me. This isn't actually an error!") {
                // This is an expected, albeit unfortunate, control flow mechanism for winit on wasm.
                console.debug("ignoring expected error:", e);
            } else {
                console.error("error while loading: ", e);
                this.updateState(SimulationLoadState.error);
                alert(e);
            }
        }
    }

    updateState(newValue: SimulationLoadState) {
        console.debug(`state change: ${SimulationLoadState[this.state]} -> ${SimulationLoadState[newValue]}`);
        this.state = newValue;
        this.render();
    }

    async load() {
        console.assert(this.state == SimulationLoadState.unloaded, "already loaded");
        // TODO: copy incremental loading logic from ABStreet for progress indication
        let response: Response = await fetch(this.config.wasmURLString());
        this.updateState(SimulationLoadState.loading);

        // TODO: Prefer streaming instantiation where available (not safari)? Seems like it'd be faster.
        // const { instance } = await WebAssembly.instantiateStreaming(response, imports);
        
        let blob: Blob = await response.blob();
        let bytes: ArrayBuffer = await blob.arrayBuffer();
        //let imports = {};
        //let instance = await WebAssembly.instantiate(bytes, imports);
        await init(bytes);

        this.updateState(SimulationLoadState.loaded);
    }

    async start() {
        console.assert(this.state == SimulationLoadState.loaded, "not yet loaded");
        // TODO - actually do something
        console.log("sim starting");
    }

    public render() {
        this.el.style["border-style"] = "solid";
        this.el.style["border-thickness"] = "4px";
        this.el.style["border-color"] = ((): string => {
            switch (this.state) {
                case SimulationLoadState.unloaded: return "yellow";
                case SimulationLoadState.loading: return "green";
                case SimulationLoadState.loaded: return "white";
                case SimulationLoadState.error: return "red";
            }
        })();
    }
}

function appendLoading(el) {
    let loadingEl = document.createElement("p");
    let text = document.createTextNode("Loading...");
    loadingEl.append(text);
    loadingEl.id = "loading";

    el.append(loadingEl);
}
